-- DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR(30) NOT NULL,
  SALARY NUMERIC(8,2),
  PHONE NUMERIC(15),
  EMAIL VARCHAR(50),
  DEPT_ID INTEGER NOT NULL
);
