spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: vincentlau
    password: Prun1234.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:DDL_BOOKS.sql
      data-locations: classpath:DML_BOOKS.sql
      mode: always
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true

server:
  port: 8090
