DROP TABLE BOOKS;

CREATE TABLE BOOKS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(30) NOT NULL,
  BOOK_NAME VARCHAR(50) NOT NULL,
  PUBLIC_DATE DATE NOT NULL,
  CONSTRAINT PK_BOOKS PRIMARY KEY(ID)
);