CREATE TABLE BOOKS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BOOK_NAME VARCHAR(50) NOT NULL,
  PUBLIC_DATE DATE NOT NULL,
  AUTHOR_ID INTEGER NOT NULL,
  CONSTRAINT PK_BOOKS PRIMARY KEY(ID),
  CONSTRAINT FK_BOOKS FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID)
);