DELETE FROM BOOKS WHERE ID IN (1,2);

INSERT INTO BOOKS (ID, AUTHOR_NAME, BOOK_NAME, PUBLIC_DATE) 
VALUES (1, "ALAN", "ALAN'S BOOK", '2022-11-02');

INSERT INTO BOOKS (ID, AUTHOR_NAME, BOOK_NAME, PUBLIC_DATE) 
VALUES (2, "OWIE", "OWIE'S BOOK", '2022-10-31');

COMMIT;
