-- TABLE DEPARTMENTS
DEPT_ID, DEPT_NAME
CS, 'COMPUTER SCIENCE'

CREATE TABLE DEPARTMENTS (
  DEPT_ID VARCHAR(3),
  DEPT_NAME VARCHAR(50),
  CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPT_ID)
);

-- TABLE2 COURSES -> FK (DEPT_ID) REFERENCE DEPARTMENTS (DEPT_ID)
COURSE_ID, DEPT_ID, COURSE_NAME
JAVA01, CS, 'JAVA COURSE'

CREATE TABLE COURSES (
  COURSE_ID VARCHAR(6),
  DEPT_ID VARCHAR(3),
  COURSE_NAME VARCHAR(50),
  CONSTRAINT PK_COURSES PRIMARY KEY (COURSE_ID),
  CONSTRAINT FK_COURSES FOREIGN KEY (COURSE_ID) REFERENCE DEPARTMENTS(DEPT_ID)
);